#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x579C160D4C9E23E8 (jelmer@fsfe.org)
#
Name     : dulwich
Version  : 0.20.3
Release  : 23
URL      : https://files.pythonhosted.org/packages/42/4c/1da52a9a47983618a4fbbb971e29c617b43f9a63201122cccddcb53fd006/dulwich-0.20.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/42/4c/1da52a9a47983618a4fbbb971e29c617b43f9a63201122cccddcb53fd006/dulwich-0.20.3.tar.gz
Source1  : https://files.pythonhosted.org/packages/42/4c/1da52a9a47983618a4fbbb971e29c617b43f9a63201122cccddcb53fd006/dulwich-0.20.3.tar.gz.asc
Summary  : Python Git Library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: dulwich-bin = %{version}-%{release}
Requires: dulwich-license = %{version}-%{release}
Requires: dulwich-python = %{version}-%{release}
Requires: dulwich-python3 = %{version}-%{release}
Requires: certifi
Requires: fastimport
Requires: urllib3
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : fastimport
BuildRequires : gevent
BuildRequires : urllib3

%description
.. image:: https://travis-ci.org/dulwich/dulwich.png?branch=master
:alt: Build Status
:target: https://travis-ci.org/dulwich/dulwich

%package bin
Summary: bin components for the dulwich package.
Group: Binaries
Requires: dulwich-license = %{version}-%{release}

%description bin
bin components for the dulwich package.


%package license
Summary: license components for the dulwich package.
Group: Default

%description license
license components for the dulwich package.


%package python
Summary: python components for the dulwich package.
Group: Default
Requires: dulwich-python3 = %{version}-%{release}

%description python
python components for the dulwich package.


%package python3
Summary: python3 components for the dulwich package.
Group: Default
Requires: python3-core
Provides: pypi(dulwich)
Requires: pypi(certifi)
Requires: pypi(urllib3)

%description python3
python3 components for the dulwich package.


%prep
%setup -q -n dulwich-0.20.3
cd %{_builddir}/dulwich-0.20.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592237164
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dulwich
cp %{_builddir}/dulwich-0.20.3/COPYING %{buildroot}/usr/share/package-licenses/dulwich/9e9b8604dc428d3f50acf86a2e36d56e008672d6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dul-receive-pack
/usr/bin/dul-upload-pack
/usr/bin/dulwich

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dulwich/9e9b8604dc428d3f50acf86a2e36d56e008672d6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
