#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x579C160D4C9E23E8 (jelmer@fsfe.org)
#
Name     : dulwich
Version  : 0.19.5
Release  : 1
URL      : https://files.pythonhosted.org/packages/b7/61/cba0a07f3b3a719d8a5442499057f9ab67b53c7e7c266f98d33642765484/dulwich-0.19.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/b7/61/cba0a07f3b3a719d8a5442499057f9ab67b53c7e7c266f98d33642765484/dulwich-0.19.5.tar.gz
Source99 : https://files.pythonhosted.org/packages/b7/61/cba0a07f3b3a719d8a5442499057f9ab67b53c7e7c266f98d33642765484/dulwich-0.19.5.tar.gz.asc
Summary  : [![Build Status](https://travis-ci.org/dulwich/dulwich.png?branch=master)](https://travis-ci.org/dulwich/dulwich)
Group    : Development/Tools
License  : Apachev2 GPL-2.0 later
Requires: dulwich-bin
Requires: dulwich-python3
Requires: dulwich-python
Requires: certifi
Requires: urllib3
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : gevent
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : urllib3

%description
Openstack Swift as backend for Dulwich
======================================
Fabien Boucher <fabien.boucher@enovance.com>

%package bin
Summary: bin components for the dulwich package.
Group: Binaries

%description bin
bin components for the dulwich package.


%package python
Summary: python components for the dulwich package.
Group: Default
Requires: dulwich-python3

%description python
python components for the dulwich package.


%package python3
Summary: python3 components for the dulwich package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dulwich package.


%prep
%setup -q -n dulwich-0.19.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532395155
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dul-receive-pack
/usr/bin/dul-upload-pack
/usr/bin/dulwich

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
